# MySQL 配置
[mysql]
host = localhost
user = your_mysql_user
password = your_mysql_password
database = health_kg

# Redis 配置
[redis]
host = localhost
port = 6379
password = your_redis_password
db = 0

# Milvus 配置
[milvus]
host = localhost
port = 19530
database_name = health
collection_name = health_rag

# 日志配置
[logger]
log_file = logs\app.log

# 检索参数配置
[retrieval]
parent_chunk_size = 1200
child_chunk_size = 300
chunk_overlap = 50
retrieval_k = 5
candidate_m = 2

# LLM 配置
[llm]
model = qwen-plus
dashscope_api_key = your_dashscope_api_key_here
dashscope_base_url = https://dashscope.aliyuncs.com/compatible-mode/v1

# model 配置
[model]
bert_base_chinese = ./rag_qa/models/bert-base-chinese
bge_m3 = ./rag_qa/models/bge-m3
bge_reranker_large = ./rag_qa/models/bge-reranker-large
nlp_bert_document_segmentation_chinese_base = ./rag_qa/models/nlp_bert_document-segmentation_chinese-base

# 应用 配置
[app]
valid_sources = ["感冒", "慢性肾脏病", "糖尿病", "肥胖","高尿酸血症_痛风", "高脂血症", "高血压","营养指南"]
customer_service_phone = 12345678
